### ISSUE TITLE
Use Git Large File Support?

### ISSUE THREAD

**Issue by j08lue** [DHI-GRAS/sample-satellite-imagery#5]
Pros:
1. better tracking of changes to binary files

Cons:
1. LFS quota (1 GB / month) for our organization might get exhausted quickly if the imagery is used in CI or so.

**Comment by dionhaefner** [comment]
I wouldn't expect the images to change often (if at all). If we stick to the 10MB/image rule, we should be able to get by without LFS. If the repo should grow to unmanageable sizes, we can still scrub it and host the data somewhere else. So that's a nay vote from me.

**Comment by j08lue** [comment]
No LFS it is.
